### ISSUE TITLE
Github workflow observations

### ISSUE THREAD

**Issue by brittyazel** [Meorawr/LibDBCompartment#2]
Hi @Meorawr,

I honestly have no idea how I ended up looking at the GitHub workflows in this repo, but somehow I did and I thought I would just point out a couple quick things. Also, please feel free to ignore me entirely lol.

In pull_request.yml and release.yml you are using actions/checkout@v2 still, and I think they're trying to get everyone to move over to actions/checkout@v3 before they fully deprecate it. Switching to v3 for me was totally plug-and-play, so that should be pretty easy.

Also, in pull_request.yml and release.yml you are using actions/setup-ruby@v1 which from my understanding is deprecated in favor of ruby/setup-ruby@v1 which is maintained by upstream Ruby themselves. (Also, I don't think your release.yml 'needs' the ruby dependency, but you probably know something I don't).

Updating these might shave 1s off your runners, so prioritize this however you will ;-)

**Comment by Meorawr** [comment]
Thanks for the heads up - I've upgraded everything now across a bunch of repos. The ruby dependency also wasn't actually necessary, it just stuck around due to being copy/pasted from another repository which did need it.
