### ISSUE TITLE
Question, LibDBIcon vs LibDBCompartment

### ISSUE THREAD

**Issue by brittyazel** [Meorawr/LibDBCompartment#3]
Hey @Meorawr, thanks so much for creating this library.

My question to you is, now that LibDBIcon has added support for the addon compartment natively, is there a strong reason to use LibDBCompartment over LibDBIcon? This isn't meant to be a 'gotcha' type question, I'm genuinely curious if I should migrate to yours over using LibDBIcon's compartment feature, and whether or not you plan on supporting this library in the long-term or if you plan to merge your version into LibDBIcon itself.

Thanks!

**Comment by Meorawr** [comment]
I'd certainly agree with and recommend just using LibDBIcon if you have need of both a minimap button and compartment integration. Given that Classic doesn't have the addon compartment and that users have largely been trained over ~20 years to expect minimap buttons, I'd expect a lot of addons will settle on LibDBIcon as their all-in-one solution.

There's no plans to discontinue or stop supporting this project though. Its scope is small enough that it's _effectively_ feature-complete at this point, and I'd expect that the cost of ongoing support is minimal enough that it won't be too onerous.

**Comment by brittyazel** [comment]
Great answer, thanks!
